# Generated by Django 3.2.6 on 2021-08-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas', '0003_activity_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
