# Generated by Django 3.2.6 on 2021-08-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas', '0004_alter_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
